# 页面默认前缀目录
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
    url: jdbc:mysql:///video?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  data:
    # solr配置
    solr:
      host: http://127.0.0.1:8090/solr/video
  # redis设置
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 200
      max-active: 1024
      max-wait: 10000
    timeout: 0
  ## 热部署相关设置
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 1024Mb
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.asimple.mapper
server:
  context-path: /video
logging:
  level:
    com.asimple.mapper : error
